# Generated by Django 3.2.19 on 2023-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20230624_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../profileplaceholder_niir6l', upload_to='images/'),
        ),
    ]
