# Generated by Django 3.2.19 on 2023-07-05 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('priority', models.IntegerField(choices=[(1, 'URGENT'), (2, 'Normal'), (3, 'Low')])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('privacy', models.IntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Complete'), (4, 'On hold')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
