# Generated by Django 3.2.19 on 2023-06-24 15:47

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230624_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, upload_to=tasks.models.Task.user_directory_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
