# Generated by Django 3.2.19 on 2023-06-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='privacy',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1),
        ),
    ]
