# Generated by Django 3.2.19 on 2023-07-04 15:11

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.Task.user_directory_path),
        ),
    ]
